### ISSUE TITLE
Minor function call issue, function name out-of-sync in vignette, .R

### ISSUE THREAD

**Issue by cgpu** [TheJacksonLaboratory/HBA-DEALS#3]
@pnrobinson @karleg 

I have test [results from RSEM](https://cloudos.lifebit.ai/public/jobs/5e998cdb5d1cd501033f0c40) and was testing the `HBA-DEALS` functions for post-processing.

The exported name for the function in `simulate_counts.R`
is `simulate`, see:

https://github.com/TheJacksonLaboratory/HBA-DEALS/blob/5bbd9ca1b3f5db31e796861af1b8922317e3d7c2/R/simulate_counts.R#L6

In the vignette the example uses `simulate.counts()`.
If the user tries to use this:

https://github.com/TheJacksonLaboratory/HBA-DEALS/blob/5bbd9ca1b3f5db31e796861af1b8922317e3d7c2/vignettes/vignette.Rmd#L36

They will get the following error message:

```console
Error: 'simulate.counts' is not an exported object from 'namespace:hbadeals'
```

This is fixed by calling the function as defined in [`R/simulate_counts.R`](https://github.com/TheJacksonLaboratory/HBA-DEALS/blob/5bbd9ca1b3f5db31e796861af1b8922317e3d7c2/R/simulate_counts.R#L6
)

```R
hbadeals::simulate()
```

Might be better to address this by changing the function definition from `simulate` -> `simulate_counts` instead of the other way around, as many other generic packages have a function named `simulate`.

If the user doesn't call the function in  the recommended format `package_name::package_function()` eg. `hbadeals::simulate()` then there might be conflicts with other packages loaded in the workspace, see warning message upon `library(hbadeals)`.

![image](https://user-images.githubusercontent.com/38183826/79565686-1518da00-80a9-11ea-80f1-0304cf653b7e.png)

**Comment by karleg** [comment]
Hi Christina,

The function ‘simulate’ is not used for post-processing, it is for simulating datasets.  The simulation example in the vignette needs to be updated, it’s best to use R help in order to read about function usage.   I will write an R script to run hbadeals on the RSEM results and send it to you.

Guy

**Comment by pnrobinson** [comment]
thanks, everybody, I appreciate it!

Peter
---

The information in this email, including attachments, may be confidential and is intended solely for the addressee(s). If you believe you received this email by mistake, please notify the sender by return email as soon as possible.

**Comment by cgpu** [comment]
Thanks both. 

@karleg ping me to test the function that implements the conversion of
RSEM outputs ➡️ input `hbadeals::hbadeals()`.

I will convert this as a Nextflow process to add to the pipeline.

Note on RSEM outputs:
The pipeline right now outputs a folder from RSEM that contain the following files per sample:

- `*.genes.results`
- `*.isoforms.results`

Let me know if I should include any other RSEM (metadata) files,  for HBA-DEALS or any other post processing step.

**Comment by pnrobinson** [comment]
@karleg  Can this issue be closed?

**Comment by karleg** [comment]
yes
